[tool.black]
line-length = 79
target-version = ['py310']
include = '\.pyi?$'
skip-string-normalization = true
exclude = '''
(
    migrations
    | \.\*
    | .env
    | .python-version
    | message_app/templates
)
'''