# Generated by Django 4.0.4 on 2022-06-07 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=30)),
                ('user_phone', models.SlugField()),
                ('user_email', models.EmailField(max_length=254)),
                ('user_report', models.CharField(choices=[('RE', 'Receive error'), ('SE', 'Send error'), ('OE', 'Other error')], default='OE', max_length=2)),
                ('message', models.TextField()),
            ],
        ),
    ]
