# Generated by Django 4.0.4 on 2022-06-07 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='user_phone',
            field=models.CharField(max_length=15),
        ),
    ]
