# Generated by Django 4.0.4 on 2022-06-10 14:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_app', '0003_message_message_sent_message_message_sent_error'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message_sent',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_sent_error',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='message',
            name='user_phone',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('[+]\\d[(]\\d{3}[)]\\d{3}[-]\\d{2}[-]\\d{2}', 'Use correct format!')]),
        ),
    ]
