# Generated by Django 4.0.4 on 2022-06-14 07:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_app', '0007_alter_message_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='user_phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(code='invalid_regex', message='Use correct format for phone field!', regex='[+]\\d[(]\\d{3}[)]\\d{3}[-]\\d{2}[-]\\d{2}')]),
        ),
    ]
