# Generated by Django 4.0.4 on 2022-06-20 08:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_app', '0008_alter_message_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.TextField(verbose_name='message'),
        ),
        migrations.AlterField(
            model_name='message',
            name='user_email',
            field=models.EmailField(max_length=254, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='message',
            name='user_name',
            field=models.CharField(max_length=30, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='message',
            name='user_phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(code='invalid_regex', message='Use correct format for phone field!', regex='[+]\\d[(]\\d{3}[)]\\d{3}[-]\\d{2}[-]\\d{2}')], verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='message',
            name='user_report',
            field=models.CharField(choices=[('RE', 'Receive error'), ('SE', 'Send error'), ('OE', 'Other error')], default='OE', max_length=2, verbose_name='report type'),
        ),
    ]
