# Generated by Django 4.0.4 on 2022-08-18 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_app', '0009_alter_message_message_alter_message_user_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='message',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='message',
            name='message_sent',
        ),
        migrations.RemoveField(
            model_name='message',
            name='message_sent_error',
        ),
        migrations.AddField(
            model_name='message',
            name='is_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='send_error',
            field=models.TextField(default='', max_length=10000),
        ),
    ]
