# Generated by Django 4.0.4 on 2022-08-19 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_app', '0010_rename_message_message_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='send_error',
            field=models.TextField(editable=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.TextField(max_length=10000, verbose_name='message'),
        ),
    ]
